name: Deploy E-Healthcare to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t hemanth42079/ehealthcare:latest .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push hemanth42079/ehealthcare:latest

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 7: Register new ECS task definition with updated image
      - name: Register new ECS task definition
        id: register-task
        run: |
          NEW_TASK_DEF=$(cat <<EOF
          {
            "family": "medusa-task",
            "networkMode": "awsvpc",
            "executionRoleArn": "arn:aws:iam::138351723773:role/ecsTaskExecutionRole",
            "containerDefinitions": [
              {
                "name": "medusa",
                "image": "hemanth42079/ehealthcare:latest",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 5000,
                    "hostPort": 5000,
                    "protocol": "tcp"
                  }
                ]
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "512",
            "memory": "1024"
          }
EOF
          )

          echo "$NEW_TASK_DEF" > new-task-def.json

          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --region us-east-1 | jq -r '.taskDefinition.taskDefinitionArn')

          echo "task_definition_arn=$TASK_DEF_ARN" >> $GITHUB_OUTPUT

      # Step 8: Update ECS service
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa-service \
            --task-definition ${{ steps.register-task.outputs.task_definition_arn }} \
            --force-new-deployment \
            --region us-east-1

      # Step 9: Wait for ECS service to stabilize
      - name: Wait for ECS service to stabilize
        run: |
          aws ecs wait services-stable \
            --cluster medusa-cluster \
            --services medusa-service \
            --region us-east-1
