name: Deploy E-Healthcare to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t hemanth42079/ehealthcare:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push hemanth42079/ehealthcare:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Register new ECS task definition (with port 5000)
        id: register-task
        run: |
          echo '{
            "family": "medusa-task",
            "networkMode": "awsvpc",
            "executionRoleArn": "arn:aws:iam::138351723773:role/ecsTaskExecutionRole",
            "containerDefinitions": [
              {
                "name": "medusa",
                "image": "hemanth42079/ehealthcare:latest",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 5000,
                    "hostPort": 5000,
                    "protocol": "tcp"
                  }
                ]
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "512",
            "memory": "1024"
          }' > taskdef.json

          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef.json \
            --region us-east-1 | jq -r '.taskDefinition.taskDefinitionArn')

          echo "task_definition_arn=$TASK_DEF_ARN" >> $GITHUB_OUTPUT

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa-service \
            --task-definition ${{ steps.register-task.outputs.task_definition_arn }} \
            --force-new-deployment \
            --region us-east-1

      - name: Wait for ECS service to stabilize
        run: |
          aws ecs wait services-stable \
            --cluster medusa-cluster \
            --services medusa-service \
            --region us-east-1
